"""Schemas for OceanIQ technical PDF report generation."""

from typing import Optional
from pydantic import Field

from api.schemas.reconstruction import ReconstructionResponse
from api.schemas.transect import TransectResponse
from api.schemas.departure import DepartureResponse


class ReportPdfRequest(ReconstructionResponse):
    """Payload for PDF report generation.

    Inherits all fields of ReconstructionResponse so existing clients passing
    a ReconstructionResponse dict are directly accepted without schema mismatch.
    Optional fields allow the frontend session to provide active transect
    or departure context when generated by the user.
    """

    transect: Optional[TransectResponse] = Field(
        None,
        description="Optional active vertical subsurface transect generated during session",
    )
    departure: Optional[DepartureResponse] = Field(
        None,
        description="Optional active subsurface reconstruction departure analysis",
    )
